name: Test setup-elvish-action
description: Tests for setup-elvish-action.

runs:
  using: composite
  steps:
    - shell: bash
      run: echo "🎭 Setting up an Elvish action..."

    - uses: ./actions/setup-elvish-action

    - shell: bash
      working-directory: ${{ github.action_path }}
      run: elvish action.elv
