name: Test setup-elvish-context
description: Tests for setup-elvish-context.

runs:
  using: composite
  steps:
    - shell: bash
      run: echo "🎭 Setting up an Elvish context with default inputs..."

    - uses: ./actions/setup-elvish-context

    - shell: elvish {0}
      run: |
        var message = '✅ Elvish confirms: the shell is ready! 🚀'

        echo $message

    - shell: elvish {0}
      working-directory: ${{ github.action_path }}
      run: |
        echo 🎭 Creating a core directory and setting up the Elvish context again...

        mkdir ../../../core

    - uses: ./actions/setup-elvish-context

    - shell: elvish {0}
      run: echo ✅ All tests OK!
