name: Test setup-elvish-context
description: Tests for setup-elvish-context.

runs:
  using: composite
  steps:
    - shell: elvish {0}
      run: echo 🎭 Setting up an Elvish context with default Ethereal..."

    - uses: ./actions/setup-elvish-context

    - shell: elvish {0}
      run: |
        var message = '✅ Elvish confirms: the shell is ready! 🚀'

        echo $message

    - shell: elvish {0}
      run: |
        echo 🎭 Trying to access the aurora-github core library...

        use github.com/giancosta86/aurora-github/math-test

        if (== (math-test:binary-add 90 2) 92) {
          echo ✅ aurora-github library accessible!
        } else {
         fail 'Error while accessing the library!'
        }

    - shell: elvish {0}
      run: |
        echo 🎭 Trying to access the ethereal library...

        use epm

        if (not (epm:is-installed github.com/giancosta86/ethereal)) {
          fail 'Ethereal should be installed!'
        }

        use github.com/giancosta86/ethereal/v1/lang

        if (== (lang:ternary $false 90 98) 98) {
          echo ✅ ethereal library accessible!
        } else {
         fail 'Error while accessing the library!'
        }

    - shell: elvish {0}
      run: echo 🎭 Setting up an Elvish context with default Ethereal - again...

    - uses: ./actions/setup-elvish-context

    - shell: elvish {0}
      run: echo ✅ Default Elvish context set up again!

    - shell: elvish {0}
      run: |
        use epm

        echo 🗑 Uninstalling Ethereal...

        epm:uninstall github.com/giancosta86/ethereal

    - shell: elvish {0}
      run: echo 🎭 Setting up an Elvish context without Ethereal...

    - uses: ./actions/setup-elvish-context
      with:
        ethereal-version: ""

    - shell: elvish {0}
      run: |
        use epm

        if (epm:is-installed github.com/giancosta86/ethereal) {
          fail 'Ethereal should not be installed!'
        } else {
          echo ✅ Elvish context ready, without Ethereal!
        }
