name: Verify

on:
  pull_request:
    types: [opened, synchronize]
    branches: main

jobs:
  verify-library:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v7

      - uses: giancosta86/aurora-github/actions/run-elvish-tests@v12

  test-setup-elvish-context:
    runs-on: ubuntu-24.04
    needs:
      - verify-library
    steps:
      - uses: actions/checkout@v7

      - uses: ./.github/test-actions/test-setup-elvish-context

  test-setup-elvish-action:
    runs-on: ubuntu-24.04
    needs:
      - test-setup-elvish-context
    steps:
      - uses: actions/checkout@v7

      - uses: ./.github/test-actions/test-setup-elvish-action

  verify-github-actions:
    runs-on: ubuntu-24.04
    needs:
      - test-setup-elvish-context
      - test-setup-elvish-action
    steps:
      - shell: elvish {0}
        run: echo ✅ Actions OK!

  verify:
    runs-on: ubuntu-24.04
    needs:
      - verify-library
      - verify-github-actions
    steps:
      - uses: giancosta86/aurora-github/actions/check-required-jobs@v12
        with:
          needs-as-json: ${{ toJSON(needs) }}
