name: Verify

on:
  pull_request:
    types: [opened, reopened, synchronize]
    branches: main

  workflow_dispatch:

jobs:
  verify-library:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v7

      - uses: giancosta86/aurora-github/actions/run-elvish-tests@v11

  test-setup-elvish-context:
    runs-on: ubuntu-24.04
    needs:
      - verify-library
    steps:
      - uses: actions/checkout@v7

      - uses: ./.github/test-actions/test-setup-elvish-context

  test-setup-elvish-action:
    runs-on: ubuntu-24.04
    needs:
      - test-setup-elvish-context
    steps:
      - uses: actions/checkout@v7

      - uses: ./.github/test-actions/test-setup-elvish-action

  verify-github-actions:
    runs-on: ubuntu-24.04
    needs:
      - test-setup-elvish-context
      - test-setup-elvish-action
    steps:
      - uses: giancosta86/aurora-github/actions/check-required-jobs@v11
        with:
          needs-as-json: ${{ toJSON(needs) }}

  verify:
    runs-on: ubuntu-24.04
    needs:
      - verify-library
      - verify-github-actions
    steps:
      - uses: giancosta86/aurora-github/actions/check-required-jobs@v11
        with:
          needs-as-json: ${{ toJSON(needs) }}
